### ISSUE TITLE
Plugin Unable to Create 'Steps' Gradient

### ISSUE THREAD

**Issue by luxlogica** [larsenwork/sketch-easing-gradient#10]
**Describe the bug**
The plugin seems to be unable to create a gradient using the 'steps' function - when selecting 'steps' from the function dropdown, it seems to simply ignore the change, and still applies whatever function was selected previously.

**To Reproduce**
1. Create a new, blank Sketch document
2. Draw a simple rectangle
3. Set the fill of the rectangle to a simple, vertical gradient - e.g., going from yellow to green
4. While the rectangle is still selected, open the Easing Gradient plugin
5. Select any of the available functions, and then select 'steps': the gradient inside the rectangle does not change to a 'step' function, and displays whatever function was previously selected.

**Expected behavior**
We would expect to see a 'step'-gradient, such as the ones we get when using the [test online Editor here](https://larsenwork.com/easing-gradients/#editor).

<img width="676" alt="screen shot 2018-07-08 at 12 28 13 pm" src="https://user-images.githubusercontent.com/2994472/42416176-df6334d0-82aa-11e8-9d42-7108c954f116.png">

**Screenshots**
Unfortunately, using the "step-gradient" function inside the plugin does not generate a step-gradient- it merely leaves whatever function had been selected previously:

<img width="305" alt="screen shot 2018-07-08 at 12 09 44 pm" src="https://user-images.githubusercontent.com/2994472/42416179-e90b414e-82aa-11e8-8099-736a011d0d21.png">

**Sketch version (please complete the following information):**
 - Version 50.2

**Comment by larsenwork** [comment]
@luxlogica thanks for the report, however I cannot reproduce it. Is it still (not) happening?

**Comment by luxlogica** [comment]
@larsenwork, it must have been some corrupt setting/preference: I updated the plugin to the latest version, then restarted Sketch, and now it magically works... 🤷‍♂️

**Comment by larsenwork** [comment]
@luxlogica cheers,  thanks for testing!
