### ISSUE TITLE
Does not work with Sketch 48.2

### ISSUE THREAD

**Issue by nickostyle** [larsenwork/sketch-easing-gradient#11]
Can see the menu but nothing happens when I click on it. Tha layer with a gradient is selected, I have already worked with this plugin in sketch 50 and everything was fine.

**Comment by larsenwork** [comment]
The plugin uses the JS api and as such requires Sketch >= 49 — I thought setting compatible version ensured it wouldn't install on older versions of Sketch :/ https://github.com/larsenwork/sketch-easing-gradient/blob/master/src/manifest.json#L9

**Comment by larsenwork** [comment]
Seems like `compatibleVersion` not really used for anything right now as per https://developer.sketchapp.com/guides/plugin-bundles/

I've updated the readme accordingly. One could also show a message when people try to use it with older versions of Sketch but that will not be a priority of mine but PRs are always welcome ;)
