### ISSUE TITLE
Plugin Warns It Cannot Parse Layer Name

### ISSUE THREAD

**Issue by luxlogica** [larsenwork/sketch-easing-gradient#9]
**Describe the bug**
In the latest version of Sketch (v50.2), whenever using the plugin on a layer for the first time, a **warning** comes up that it "_couldn't parse the layer name_". Once the plugin has been used on a layer, using it again on the same layer does not generate the warning - i.e., the warning only seems to appear on first use.

**To Reproduce**
1. Open a new, blank document in the latest version of Sketch
2. Draw a simple rectangle
3. Set the fill of the rectangle to a simple vertical linear gradient (e.g., yellow to green)
4. With the rectangle still selected, open the Easing Gradient Plugin (Plugins -> Easing Gradient -> Edit Easing Gradient)

**Screenshots**

<img width="385" alt="screen shot 2018-07-08 at 12 07 18 pm" src="https://user-images.githubusercontent.com/2994472/42416060-1ffb3c70-82a8-11e8-829a-d632bbe3e126.png">

**Sketch version (please complete the following information):**
 - Version 50.2

**Comment by larsenwork** [comment]
Yeah, that message should maybe be tweaked a bit — technically it's correct but I'll update the message.

**Comment by larsenwork** [comment]
Adjusted message in https://github.com/larsenwork/sketch-easing-gradient/commit/a4ced9117c1bf300698829676d75a6f11c7635a8
